export const HOTEL_TYPES = [
  "hotel",
  "resort",
  "apartment",
  "hostel",
  "villa",
  "guest-house",
  "homestay",
  "boutique",
  "motel",
] as const;

export const FACILITIES = [
  "wifi",
  "parking",
  "pool",
  "gym",
  "spa",
  "restaurant",
  "bar",
  "airport-shuttle",
  "ev-charging",
  "conference-room",
  "business-center",
  "wheelchair-access",
  "pet-friendly",
  "laundry-service",
  "security-24h",
  "cctv",
  "garden",
  "terrace",
  "private-beach",
] as const;

export const AMENITIES = [
  "breakfast",
  "ac",
  "tv",
  "room-service",
  "laundry",
  "minibar",
  "coffee-maker",
  "balcony",
  "sea-view",
  "city-view",
  "soundproof",
  "workspace",
  "iron",
  "hair-dryer",
  "toiletries",
  "bathtub",
  "shower",
  "kitchen",
  "microwave",
  "refrigerator",
] as const;

export const TAGS = [
  "budget",
  "luxury",
  "family",
  "couple",
  "business",
  "romantic",
  "eco-friendly",
  "trending",
  "top-rated",
  "new",
  "best-value",
  "near-airport",
  "city-center",
  "beachfront",
  "mountain-view",
  "pet-friendly",
] as const;
